### ISSUE TITLE
Needed: HTML Template For Example

### ISSUE THREAD

**Issue by eli-townsend** [edward-of-clt/stepWiz#1]
For individuals who are just looking to plug this in, need a basic template for a few steps

**Comment by edwardofclt** [comment]
Working on that now actually.

**Comment by eli-townsend** [comment]
Haha beat you by that much

**Comment by edwardofclt** [comment]
Just uploaded what I've been playing with.

**Comment by edwardofclt** [comment]
Initial documentation added.
